/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages.newpackage;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import JavaApplication5.loginPage;
import JavaApplication5.registerPage;

/**
 *
 * @author User
 */
public class accountPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form accountPage
     */
    public accountPage() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jPanel1.setBackground(Color.GRAY);
        jLabel_accountSettings.setForeground(Color.WHITE);
        jLabel_accountName.setForeground(Color.WHITE);
        jLabel_number.setForeground(Color.WHITE);
        jLabel_email.setForeground(Color.WHITE);
        jLabel_address.setForeground(Color.WHITE);
        jLabel_editUser.setForeground(Color.WHITE);
        jLabel_editUserBorder.setBorder(border);
        jLabel_report.setForeground(Color.WHITE);
        jLabel_reportBorder.setBorder(border);
        jLabel_logout.setForeground(Color.WHITE);
        jLabel_logoutBorder.setBorder(border);
        jLabel_usernameBorder.setBorder(border);
        jLabel_username.setForeground(Color.WHITE);
        jPanel2.setBackground(Color.BLACK);
        jLabel_detailFName.setForeground(Color.WHITE);
        jLabel_detailLName.setForeground(Color.white);
        jLabel_detailNumber.setForeground(Color.white);
        jLabel_detailEmail.setForeground(Color.white);
        jLabel_detailAddress.setForeground(Color.white);
        jLabel_editUser.setForeground(Color.white);
        jLabel_report.setForeground(Color.white);
        jLabel_detailAddress.setText(registerPage.address);
        jLabel_detailEmail.setText(registerPage.email);
        jLabel_detailLName.setText(registerPage.Lname);
        jLabel_detailFName.setText(registerPage.Fname);
        jLabel_detailNumber.setText(registerPage.contact);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_accountSettings = new javax.swing.JLabel();
        jLabel_accountName = new javax.swing.JLabel();
        jLabel_number = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_address = new javax.swing.JLabel();
        jLabel_usernameIcon = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_usernameBorder = new javax.swing.JLabel();
        jLabel_detailAddress = new javax.swing.JLabel();
        jLabel_detailLName = new javax.swing.JLabel();
        jLabel_detailNumber = new javax.swing.JLabel();
        jLabel_detailEmail = new javax.swing.JLabel();
        jLabel_detailFName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_editUserIcon = new javax.swing.JLabel();
        jLabel_editUser = new javax.swing.JLabel();
        jLabel_editUserBorder = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_report = new javax.swing.JLabel();
        jLabel_reportBorder = new javax.swing.JLabel();
        jLabel_logoutIcon = new javax.swing.JLabel();
        jLabel_logout = new javax.swing.JLabel();
        jLabel_logoutBorder = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_accountSettings.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_accountSettings.setText("ACCOUNT SETTINGS");
        jPanel1.add(jLabel_accountSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 20));

        jLabel_accountName.setText("ACCOUNT NAME:");
        jPanel1.add(jLabel_accountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel_number.setText("CONTACT NUMBER:");
        jPanel1.add(jLabel_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        jLabel_email.setText("EMAIL:");
        jPanel1.add(jLabel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel_address.setText("ADDRESS:");
        jPanel1.add(jLabel_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel_usernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user-100.png"))); // NOI18N
        jPanel1.add(jLabel_usernameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_username.setText("Username");
        jPanel1.add(jLabel_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 80, -1));

        jLabel_usernameBorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_usernameBorderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_usernameBorderMouseExited(evt);
            }
        });
        jPanel1.add(jLabel_usernameBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 140, 130));

        jLabel_detailAddress.setText("address");
        jPanel1.add(jLabel_detailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 110, -1));

        jLabel_detailLName.setText("name");
        jPanel1.add(jLabel_detailLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 70, -1));

        jLabel_detailNumber.setText("contact number");
        jPanel1.add(jLabel_detailNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, -1));

        jLabel_detailEmail.setText("email");
        jPanel1.add(jLabel_detailEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, -1));

        jLabel_detailFName.setText("name");
        jPanel1.add(jLabel_detailFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 150));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel_editUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manage user-50.png"))); // NOI18N
        jPanel2.add(jLabel_editUserIcon);
        jLabel_editUserIcon.setBounds(100, 100, 60, 50);

        jLabel_editUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_editUser.setText("Edit User");
        jPanel2.add(jLabel_editUser);
        jLabel_editUser.setBounds(90, 160, 80, 22);

        jLabel_editUserBorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_editUserBorderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_editUserBorderMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_editUserBorder);
        jLabel_editUserBorder.setBounds(50, 70, 160, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report-50.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(280, 100, 70, 70);

        jLabel_report.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_report.setText("REPORTS");
        jPanel2.add(jLabel_report);
        jLabel_report.setBounds(260, 160, 110, 22);

        jLabel_reportBorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_reportBorderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_reportBorderMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_reportBorder);
        jLabel_reportBorder.setBounds(230, 70, 160, 140);

        jLabel_logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-64.png"))); // NOI18N
        jPanel2.add(jLabel_logoutIcon);
        jLabel_logoutIcon.setBounds(460, 90, 70, 64);

        jLabel_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_logout.setText("LOG OUT");
        jPanel2.add(jLabel_logout);
        jLabel_logout.setBounds(460, 160, 90, 22);

        jLabel_logoutBorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutBorderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_logoutBorderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_logoutBorderMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_logoutBorder);
        jLabel_logoutBorder.setBounds(420, 70, 160, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-20, -10, 690, 387);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 620, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_editUserBorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_editUserBorderMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_editUserBorder.setBorder(border);
        jLabel_editUser.setForeground(Color.RED);
    }//GEN-LAST:event_jLabel_editUserBorderMouseEntered

    private void jLabel_editUserBorderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_editUserBorderMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_editUserBorder.setBorder(border);
        jLabel_editUser.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_editUserBorderMouseExited

    private void jLabel_reportBorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_reportBorderMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_reportBorder.setBorder(border);
        jLabel_report.setForeground(Color.RED);
    }//GEN-LAST:event_jLabel_reportBorderMouseEntered

    private void jLabel_reportBorderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_reportBorderMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_reportBorder.setBorder(border);
        jLabel_report.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_reportBorderMouseExited

    private void jLabel_logoutBorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutBorderMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_logoutBorder.setBorder(border);
        jLabel_logout.setForeground(Color.RED);
    }//GEN-LAST:event_jLabel_logoutBorderMouseEntered

    private void jLabel_logoutBorderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutBorderMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_logoutBorder.setBorder(border);
        jLabel_logout.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_logoutBorderMouseExited

    private void jLabel_logoutBorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutBorderMouseClicked
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.dispose();
        loginPage login = new loginPage();
        login.setVisible(true);
    }//GEN-LAST:event_jLabel_logoutBorderMouseClicked

    private void jLabel_usernameBorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_usernameBorderMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_usernameBorder.setBorder(border);
        jLabel_username.setForeground(Color.RED);
    }//GEN-LAST:event_jLabel_usernameBorderMouseEntered

    private void jLabel_usernameBorderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_usernameBorderMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_usernameBorder.setBorder(border);
        jLabel_username.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_usernameBorderMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_accountName;
    private javax.swing.JLabel jLabel_accountSettings;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JLabel jLabel_detailAddress;
    private javax.swing.JLabel jLabel_detailEmail;
    private javax.swing.JLabel jLabel_detailFName;
    private javax.swing.JLabel jLabel_detailLName;
    private javax.swing.JLabel jLabel_detailNumber;
    private javax.swing.JLabel jLabel_editUser;
    private javax.swing.JLabel jLabel_editUserBorder;
    private javax.swing.JLabel jLabel_editUserIcon;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JLabel jLabel_logoutBorder;
    private javax.swing.JLabel jLabel_logoutIcon;
    private javax.swing.JLabel jLabel_number;
    private javax.swing.JLabel jLabel_report;
    private javax.swing.JLabel jLabel_reportBorder;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JLabel jLabel_usernameBorder;
    private javax.swing.JLabel jLabel_usernameIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
