/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApplication5;

import internalPages.newpackage.accountPage;
import internalPages.newpackage.dashPage;
import internalPages.newpackage.reportsPage;
import internalPages.newpackage.adminPage;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author User
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    boolean released = false;

    public dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        jLabel_account.setBorder(border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel_navBar = new javax.swing.JPanel();
        jLabel_userpage = new javax.swing.JLabel();
        jLabel_reportpage = new javax.swing.JLabel();
        jLabel_dashboard = new javax.swing.JLabel();
        jLabel_account = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_close = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane_main = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel_navBar.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_navBar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 255)));
        jPanel_navBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel_userpage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_userpage.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_userpage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_userpage.setText("ADMIN PAGE");
        jLabel_userpage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_userpageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_userpageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_userpageMouseExited(evt);
            }
        });

        jLabel_reportpage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_reportpage.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_reportpage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_reportpage.setText("REPORTS");
        jLabel_reportpage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_reportpageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_reportpageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_reportpageMouseExited(evt);
            }
        });

        jLabel_dashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_dashboard.setText("DASHBOARD");
        jLabel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseExited(evt);
            }
        });

        jLabel_account.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_account.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_account.setText("ACCOUNT SETTING");
        jLabel_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_accountMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_navBarLayout = new javax.swing.GroupLayout(jPanel_navBar);
        jPanel_navBar.setLayout(jPanel_navBarLayout);
        jPanel_navBarLayout.setHorizontalGroup(
            jPanel_navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_userpage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_reportpage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_account, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        jPanel_navBarLayout.setVerticalGroup(
            jPanel_navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_navBarLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_userpage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_reportpage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_account, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_navBar);
        jPanel_navBar.setBounds(0, 0, 200, 430);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(558, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_close)
                    .addComponent(jLabel3))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(200, 0, 610, 20);

        jDesktopPane_main.setBackground(new java.awt.Color(0, 153, 255));
        jDesktopPane_main.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 255)));
        jDesktopPane_main.setPreferredSize(new java.awt.Dimension(760, 420));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/welcome-50.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, -20, 580, 350);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-50, 30, 660, 588);

        jDesktopPane_main.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane_mainLayout = new javax.swing.GroupLayout(jDesktopPane_main);
        jDesktopPane_main.setLayout(jDesktopPane_mainLayout);
        jDesktopPane_mainLayout.setHorizontalGroup(
            jDesktopPane_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        jDesktopPane_mainLayout.setVerticalGroup(
            jDesktopPane_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane_main);
        jDesktopPane_main.setBounds(200, 20, 610, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_userpageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_userpageMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_userpage.setBorder(label_border);
        jLabel_userpage.setForeground(Color.red);
    }//GEN-LAST:event_jLabel_userpageMouseEntered

    private void jLabel_userpageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_userpageMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        jLabel_userpage.setBorder(label_border);
        jLabel_userpage.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_userpageMouseExited

    private void jLabel_reportpageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_reportpageMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_reportpage.setBorder(label_border);
        jLabel_reportpage.setForeground(Color.red);
    }//GEN-LAST:event_jLabel_reportpageMouseEntered

    private void jLabel_reportpageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_reportpageMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        jLabel_reportpage.setBorder(label_border);
        jLabel_reportpage.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_reportpageMouseExited

    private void jLabel_userpageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_userpageMouseClicked
        adminPage user = new adminPage();
        jDesktopPane_main.add(user).setVisible(true);
    }//GEN-LAST:event_jLabel_userpageMouseClicked

    private void jLabel_reportpageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_reportpageMouseClicked
        reportsPage report = new reportsPage();
        jDesktopPane_main.add(report).setVisible(true);
    }//GEN-LAST:event_jLabel_reportpageMouseClicked

    private void jLabel_accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_accountMouseClicked
        accountPage acc = new accountPage();
        jDesktopPane_main.add(acc).setVisible(true);
    }//GEN-LAST:event_jLabel_accountMouseClicked

    private void jLabel_accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_accountMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_account.setBorder(label_border);
        jLabel_account.setForeground(Color.red);
    }//GEN-LAST:event_jLabel_accountMouseEntered

    private void jLabel_accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_accountMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        jLabel_account.setBorder(label_border);
        jLabel_account.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_accountMouseExited

    private void jLabel_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_dashboard.setBorder(label_border);
        jLabel_dashboard.setForeground(Color.red);
    }//GEN-LAST:event_jLabel_dashboardMouseEntered

    private void jLabel_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        jLabel_dashboard.setBorder(label_border);
        jLabel_dashboard.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_dashboardMouseExited

    private void jLabel_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseClicked
        dashPage acc = new dashPage();
        jDesktopPane_main.add(acc).setVisible(true);
    }//GEN-LAST:event_jLabel_dashboardMouseClicked

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked

    }//GEN-LAST:event_jLabel_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDesktopPane jDesktopPane_main;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_account;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_dashboard;
    private javax.swing.JLabel jLabel_reportpage;
    private javax.swing.JLabel jLabel_userpage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_navBar;
    // End of variables declaration//GEN-END:variables

    private void setBorder(Border createEmptyBorder) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
