/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApplication5;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

public class loginPage extends javax.swing.JFrame {

    /**
     * Creates new form loginPage
     */
    boolean clicked = false;

    public loginPage() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.Color.WHITE);
        jLabel_showHidePassword.setBorder(border);
        jLabel_username.setBorder(border);
        jLabel_password.setBorder(border);
        jLabel_lockIcon.setBorder(border);
        jPanel_body.setBackground(Color.black);
        jLabel_username.setForeground(Color.WHITE);
        jLabel_password.setForeground(Color.WHITE);
        jLabel_loginButton.setBorder(border);
        jLabel_loginButton.setForeground(Color.WHITE);
        jLabel_minimize.setBorder(border);
        jLabel_close.setBorder(border);
        Border register_border = BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.WHITE);
        jLabel_register.setBorder(register_border);
        jLabel_close.setForeground(Color.WHITE);
        jLabel_minimize.setForeground(Color.WHITE);
        jLabel_register.setForeground(Color.WHITE);
        jLabel_showHidePassword.setForeground(Color.WHITE);
        jTextField_username.setFocusable(false);
        jPasswordField_password.setFocusable(false);
        jPanel_body.setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_body = new javax.swing.JPanel();
        jLabel_username = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel_password = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel_lockIcon = new javax.swing.JLabel();
        jLabel_showHidePassword = new javax.swing.JLabel();
        jLabel_loginButton = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_register = new javax.swing.JLabel();
        jLabel_error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_body.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_body.setEnabled(false);
        jPanel_body.setOpaque(false);
        jPanel_body.setLayout(null);

        jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_username.setText("Username:");
        jLabel_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_usernameMouseClicked(evt);
            }
        });
        jPanel_body.add(jLabel_username);
        jLabel_username.setBounds(160, 140, 120, 22);

        jTextField_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_usernameMouseClicked(evt);
            }
        });
        jPanel_body.add(jTextField_username);
        jTextField_username.setBounds(210, 170, 200, 30);

        jLabel_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_password.setText("Password:");
        jPanel_body.add(jLabel_password);
        jLabel_password.setBounds(160, 210, 120, 20);

        jPasswordField_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_passwordMouseClicked(evt);
            }
        });
        jPanel_body.add(jPasswordField_password);
        jPasswordField_password.setBounds(210, 240, 200, 30);

        jLabel_lockIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_lockIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lock.png"))); // NOI18N
        jPanel_body.add(jLabel_lockIcon);
        jLabel_lockIcon.setBounds(250, 50, 90, 80);

        jLabel_showHidePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_showHidePassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_showHidePassword.setText("Hide");
        jLabel_showHidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_showHidePasswordMouseClicked(evt);
            }
        });
        jPanel_body.add(jLabel_showHidePassword);
        jLabel_showHidePassword.setBounds(420, 250, 50, 20);

        jLabel_loginButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_loginButton.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_loginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_loginButton.setText("LOGIN");
        jLabel_loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_loginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_loginButtonMouseExited(evt);
            }
        });
        jPanel_body.add(jLabel_loginButton);
        jLabel_loginButton.setBounds(220, 310, 70, 20);

        jLabel_minimize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setText("-");
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });
        jPanel_body.add(jLabel_minimize);
        jLabel_minimize.setBounds(570, 0, 20, 17);

        jLabel_close.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });
        jPanel_body.add(jLabel_close);
        jLabel_close.setBounds(590, 0, 20, 17);

        jLabel_register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_register.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_register.setText("register here!!");
        jLabel_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_registerMouseExited(evt);
            }
        });
        jPanel_body.add(jLabel_register);
        jLabel_register.setBounds(300, 310, 100, 17);

        jLabel_error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_error.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_body.add(jLabel_error);
        jLabel_error.setBounds(210, 280, 210, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel_body.add(jLabel1);
        jLabel1.setBounds(-40, 70, 690, 390);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel_body.add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_body, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_body, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_showHidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_showHidePasswordMouseClicked
        clicked = !clicked;

        if (clicked) {
            jPasswordField_password.setEchoChar((char) 0);
            jLabel_showHidePassword.setText("Show");
            Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
            jLabel_showHidePassword.setBorder(border);
            jLabel_showHidePassword.setForeground(Color.WHITE);
        } else {
            jPasswordField_password.setEchoChar('*');
            Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED);
            jLabel_showHidePassword.setBorder(border);
            jLabel_showHidePassword.setText("Hide");
            jLabel_showHidePassword.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_jLabel_showHidePasswordMouseClicked

    private void jLabel_loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginButtonMouseClicked
        if (jTextField_username.getText().equals(registerPage.username) && jPasswordField_password.getText().equals(registerPage.password)) {
            dashboard dash = new dashboard();
            dash.setVisible(true);
            dash.pack();
            dash.setLocationRelativeTo(null);
            dash.setDefaultCloseOperation(loginPage.EXIT_ON_CLOSE);
        } else {
            jLabel_error.setText("Your account don't exist!!");
        }
    }//GEN-LAST:event_jLabel_loginButtonMouseClicked

    private void jLabel_loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginButtonMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_loginButton.setBorder(border);
        jLabel_loginButton.setForeground(Color.RED);
    }//GEN-LAST:event_jLabel_loginButtonMouseEntered

    private void jLabel_loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginButtonMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_loginButton.setBorder(border);
        jLabel_loginButton.setForeground(Color.WHITE);

    }//GEN-LAST:event_jLabel_loginButtonMouseExited

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.toBack();
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        this.hide();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_minimize.setBorder(border);
        jLabel_minimize.setForeground(Color.RED);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_minimize.setBorder(border);
        jLabel_minimize.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLUE);
        jLabel_close.setBorder(border);
        jLabel_close.setForeground(Color.RED);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_close.setBorder(border);
        jLabel_close.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registerMouseEntered
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLUE);
        jLabel_register.setBorder(border);
        jLabel_register.setForeground(Color.RED);
    }//GEN-LAST:event_jLabel_registerMouseEntered

    private void jLabel_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registerMouseExited
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE);
        jLabel_register.setBorder(border);
        jLabel_register.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_registerMouseExited

    private void jLabel_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_usernameMouseClicked

    }//GEN-LAST:event_jLabel_usernameMouseClicked

    private void jLabel_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registerMouseClicked
        registerPage register = new registerPage();
        register.setVisible(true);
        register.pack();
        register.setLocationRelativeTo(null);
        register.setDefaultCloseOperation(loginPage.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel_registerMouseClicked

    private void jTextField_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usernameMouseClicked
        jTextField_username.setFocusable(true);
    }//GEN-LAST:event_jTextField_usernameMouseClicked

    private void jPasswordField_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_passwordMouseClicked
        jPasswordField_password.setFocusable(true);
    }//GEN-LAST:event_jPasswordField_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JLabel jLabel_lockIcon;
    private javax.swing.JLabel jLabel_loginButton;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_register;
    private javax.swing.JLabel jLabel_showHidePassword;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_body;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
