/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApplication5;

/**
 *
 * @author User
 */
public class registerPage extends javax.swing.JFrame {

    boolean clicked = false;
    /**
     * Creates new form registerPage
     */
    public static String Fname;
    public static String Lname;
    public static String username;
    public static String password;
    public static String contact;
    public static String address;
    public static String email;
    

            // convert the character to uppercase
    

    public registerPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_FName = new javax.swing.JTextField();
        jTextField_LName = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jTextField_ContactNumber = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jPasswordField_password = new javax.swing.JPasswordField();
        jPasswordField_confirmPassword = new javax.swing.JPasswordField();
        jLabel_fName = new javax.swing.JLabel();
        jLabel_Lname = new javax.swing.JLabel();
        jLabel_address = new javax.swing.JLabel();
        jLabel_address1 = new javax.swing.JLabel();
        jLabel_contactNumber = new javax.swing.JLabel();
        jLabel_passwprd = new javax.swing.JLabel();
        jLabel_confirmPassword = new javax.swing.JLabel();
        jLabel_register = new javax.swing.JLabel();
        jLabel_title = new javax.swing.JLabel();
        jLabel_error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jTextField_FName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField_FName);
        jTextField_FName.setBounds(70, 90, 150, 21);

        jTextField_LName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField_LName);
        jTextField_LName.setBounds(230, 90, 150, 21);

        jTextField_username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField_username);
        jTextField_username.setBounds(70, 130, 150, 21);

        jTextField_address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField_address);
        jTextField_address.setBounds(70, 170, 310, 21);

        jTextField_ContactNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField_ContactNumber);
        jTextField_ContactNumber.setBounds(230, 130, 150, 21);

        jTextField_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField_email);
        jTextField_email.setBounds(70, 210, 310, 21);
        jPanel1.add(jPasswordField_password);
        jPasswordField_password.setBounds(70, 250, 150, 20);
        jPanel1.add(jPasswordField_confirmPassword);
        jPasswordField_confirmPassword.setBounds(70, 290, 150, 20);

        jLabel_fName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_fName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fName.setText("First Name:");
        jPanel1.add(jLabel_fName);
        jLabel_fName.setBounds(70, 70, 100, 17);

        jLabel_Lname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Lname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Lname.setText("Last Name:");
        jPanel1.add(jLabel_Lname);
        jLabel_Lname.setBounds(230, 70, 80, 17);

        jLabel_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_address.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_address.setText("Address:");
        jPanel1.add(jLabel_address);
        jLabel_address.setBounds(70, 150, 100, 20);

        jLabel_address1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_address1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_address1.setText("Email:");
        jPanel1.add(jLabel_address1);
        jLabel_address1.setBounds(70, 190, 100, 20);

        jLabel_contactNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_contactNumber.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_contactNumber.setText("Contact Number:");
        jPanel1.add(jLabel_contactNumber);
        jLabel_contactNumber.setBounds(230, 110, 140, 17);

        jLabel_passwprd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_passwprd.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_passwprd.setText("Password:");
        jPanel1.add(jLabel_passwprd);
        jLabel_passwprd.setBounds(70, 230, 80, 17);

        jLabel_confirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_confirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_confirmPassword.setText("Confirm Password:");
        jPanel1.add(jLabel_confirmPassword);
        jLabel_confirmPassword.setBounds(70, 270, 150, 17);

        jLabel_register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_register.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_register.setText("REGISTER");
        jLabel_register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registerMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_register);
        jLabel_register.setBounds(170, 350, 110, 20);

        jLabel_title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setText("REGISTRATION FORM!!");
        jPanel1.add(jLabel_title);
        jLabel_title.setBounds(90, 30, 300, 29);

        jLabel_error.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel_error);
        jLabel_error.setBounds(110, 320, 250, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/image.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-100, 190, 560, 240);

        jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_username.setText("Username:");
        jPanel1.add(jLabel_username);
        jLabel_username.setBounds(70, 110, 100, 17);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 425));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registerMouseClicked
        clicked = !clicked;
        if (!clicked) {
            if (jPasswordField_password.getText().equals(jPasswordField_confirmPassword.getText())) {
                Fname = jTextField_FName.getText();
                Lname = jTextField_LName.getText();
                contact= jTextField_ContactNumber.getText();
                address =jTextField_address.getText();
                email=jTextField_email.getText();
                username = jTextField_username.getText();
                password = jPasswordField_password.getText();
                
                loginPage login = new loginPage();
                login.setVisible(true);
                login.pack();
                login.setLocationRelativeTo(null);
                this.dispose();
            } else {
                jLabel_error.setText("Your password doesn't match!!");
            }
        }
    }//GEN-LAST:event_jLabel_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Lname;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JLabel jLabel_address1;
    private javax.swing.JLabel jLabel_confirmPassword;
    private javax.swing.JLabel jLabel_contactNumber;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JLabel jLabel_fName;
    private javax.swing.JLabel jLabel_passwprd;
    private javax.swing.JLabel jLabel_register;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_confirmPassword;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_ContactNumber;
    private javax.swing.JTextField jTextField_FName;
    private javax.swing.JTextField jTextField_LName;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
